name: CI/CD Backend

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 17
          
      - name: Unit tests
        run: |
          mvn -B test --file backend-project/microservices/pom.xml
          mvn -B test --file backend-project/microservices/eureka-discovery-service/pom.xml
          mvn -B test --file backend-project/microservices/config-service/pom.xml
          mvn -B test --file backend-project/microservices/gateway/pom.xml
          mvn -B test --file backend-project/microservices/customer-service/pom.xml
          mvn -B test --file backend-project/microservices/inventory-service/pom.xml
          mvn -B test --file backend-project/microservices/billing-service/pom.xml

      - name: Build the application
        run: |
          cd backend-project/microservices/
          mvn clean 
          mvn -B package --file pom.xml
          cd eureka-discovery-service
          mvn clean 
          mvn -B package --file pom.xml
          cd ../config-service/
          mvn clean 
          mvn -B package --file pom.xml
          cd ../gateway/
          mvn clean 
          mvn -B package --file pom.xml
          cd ../customer-service/
          mvn clean 
          mvn -B package --file pom.xml
          cd ../inventory-service/
          mvn clean 
          mvn -B package --file pom.xml
          cd ../billing-service/
          mvn clean 
          mvn -B package --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with: 
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/microservices-project:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/microservices-project:config

          
